spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/community?&useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: ysk0221.
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
server:
  servlet:
    context-path: /community
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sheep.community.pojo
  configuration:
    use-generated-keys: true
    map-underscore-to-camel-case: true

